engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    file: rubocop.yml
  scss-lint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
        javascript:
          mass_threshold: 40
ratings:
  paths:
    - Gemfile.lock
    - "**.scss"
    - "**.css"
    - "**.rb"
    - "**.coffee"
exclude_paths:
- "app/assets/javascripts/bootstrap/bootstrap.js"
- "app/assets/javascripts/external/parsley.js"
- "app/assets/javascripts/external/jquery.blockUI.js"
- "app/assets/javascripts/dmf/app_common.js"
- "app/assets/javascripts/bootstrap/bootstrap-typeahead.js"
- "app/assets/javascripts/jquery.mask.js"
- "app/assets/javascripts/jquery.bootstrap.wizard.js"
- "app/assets/javascripts/external/jquery.cookie.js"
- "app/assets/javascripts/dmf/dmf.js"
- "app/assets/javascripts/external/exception_logger.js"
- "app/assets/javascripts/highcharts/0highcharts.js"
- "app/assets/javascripts/form-frontend.js"
- "db"
- "test"
